"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 50
command_timeout = 1000
follow_symlinks = true

format = '$character$directory'
# right_format = '$terraform$c$zig$odin$golang$rust$ruby$python${custom.hugo}([\[](#49443C)$git_state$git_status$git_metrics$git_branch$git_commit[\]](#49443C))$battery'

right_format = """
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$dotnet\
$golang\
$helm\
$java\
$kotlin\
$lua\
$nim\
$nodejs\
$perl\
$php\
$python\
$rust\
$scala\
$swift\
$terraform\
$conda\
$meson\
$memory_usage\
$aws\
$gcloud\
$custom\
$status\
$os\
$battery\
$time"""

palette = "kanagawa_dragon"

[character]
success_symbol = "[[󰄛](green) ➜](yellow)"
error_symbol = "[[󰄛](red) ➜](yellow)"

[directory]
truncation_length = 8
read_only = " 󰌾"
truncation_symbol = '…/'
style = 'bold purple'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
rebase = '[rebasing](bold red)'
merge = '[merging](bold brightYellow)'
revert = '[reverting](bold blue)'
cherry_pick = '[picking](bold brightRed)'
bisect = '[bisecting](bold brightRed)'
am = '[applying](bold green)'
am_or_rebase = '[applying/rebasing](bold brightYellow)'

[git_status]
# format = '($all_status$ahead_behind )'
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
style = '8'
up_to_date = '[](brightCyan)'
untracked = '[.](surface1)'
conflicted = '[#](red)'
ahead = '[⇡│[${count}](bold white)│](green)'
behind = '[⇣│[${count}](bold white)│](yellow)'
diverged = '[⇕ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](brightRed)'
stashed = '[^](yellow)'
modified = '[*](cyan)'
staged = '[+┤[$count](bold white)│](blue)'
renamed = '[»](brightYellow)'
deleted = '[x](red)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ''
style = 'bold purple'
truncation_length = 11
truncation_symbol = '⋯'
ignore_branches = []

[git_commit]
format = ' [$hash$tag]($style)'
style = '8'
only_detached = false
commit_hash_length = 6
tag_symbol = ''

[git_metrics]
disabled = false
added_style = 'surface0'
deleted_style = 'red'
format = '([+$added]($added_style))([-$deleted]($deleted_style)) '

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold brightYellow"

[nodejs]
format = " [node](italic) [◫ ($version)](bold green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[golang]
format = '[$symbol($version )]($style)'
style = 'cyan'
symbol = ' '

[python]
format = '[$symbol($version )]($style)'
style = 'green'
symbol = ' '

[rust]
format = '[$symbol($version )]($style)'
style = 'yellow'
symbol = ' '

[terraform]
format = '[$symbol$workspace]($style)'
style = 'purple'
symbol = ' '

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[custom.hugo]
format = '[$symbol($output )]($style)'
style = 'red'
symbol = ' '
command = "hugo version | cut -d ' ' -f2 | cut -d '+' -f1"
when = "test -f $(git rev-parse --show-toplevel)/config/_default/config.*"
require_repo = true

[os]
format = " [$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[palettes.kanagawa_dragon]
red = "#c4746e"
purple = "#a292a3"
brightRed = "#e46876"
yellow = "#E6C384"
brightYellow = "#c4b28a"
green = "#87a987"
brightCyan = "#7aa89f"
cyan = "#8ea4a2"
blue = "#7FB4CA"
surface1 = "#45475a"
surface0 = "#313244"
white = "#c5c9c5"
