---
gui:
  # stuff relating to the UI
  screenMode: normal # one of 'normal' | 'half' | 'full' default is 'normal'
  scrollHeight: 2  # how many lines you scroll by
  scrollPastBottom: true  # enable scrolling past the bottom
  sidePanelWidth: 0.3333  # number from 0 to 1
  expandFocusedSidePanel: true
  mainPanelSplitMode: flexible # one of 'horizontal' | 'flexible' | 'vertical'
  language: en # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  timeFormat: 02 Jan 06  # https://pkg.go.dev/time#Time.Format
  shortTimeFormat: 13:00
  theme:
    activeBorderColor:
     - "#8ba4b0"
     - "bold"
    inactiveBorderColor:
     - "#625e5a"
    searchingActiveBorderColor:
     - "#c4b28a"
     - "bold"
    optionsTextColor:
     - "#8992a7"
    selectedLineBgColor:
     - "#282727"
    inactiveViewSelectedLineBgColor:
     - "#1d1c19"
    cherryPickedCommitFgColor:
     - "#8ba4b0"
    cherryPickedCommitBgColor:
     - "#282727"
    markedBaseCommitFgColor:
     - "#c4b28a"
    markedBaseCommitBgColor:
     - "#282727"
    unstagedChangesColor:
     - "#c4746e"
    defaultFgColor:
     - "#c5c9c5"
  commitLength:
    show: true
  mouseEvents: true
  ignoreWhitespaceInDiffView: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: true  # for rendering changes files in a tree format
  showListFooter: true  # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showBranchCommitHash: false  # show commit hashes alongside branch names
  experimentalShowBranchHeads: false  # visualize branch heads with (*) in commits list
  showBottomLine: true  # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  nerdFontsVersion: '3'
  commandLogSize: 8
  splitDiff: auto # one of 'auto' | 'always'
  skipRewordInEditorWarning: false  # for skipping the confirmation before launching the reword editor
  border: rounded # one of 'single' | 'double' | 'rounded' | 'hidden'
  notARepository: quit
  branchColorPatterns:
    ^feature/: '#11aaff' # use a light blue for branches beginning with 'docs/'
    ^bugfix/: '#f28500' # use a light blue for branches beginning with 'docs/'
    ISSUE-\d+: '#ff5733' # use a bright orange for branches containing 'ISSUE-<some-number>'
git:
  pagers:
    - colorArg: always
      useConfig: false
      pager: delta --dark --paging=never
  commit:
    signOff: true
  merging:
    manualCommit: false
    args: ""
  log:
    order: topo-order
    showGraph: when-maximised
    showWholeGraph: false
    parseEmoji: false
  skipHookPrefix: WIP
  mainBranches: [master, main]
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  overrideGpg: true
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
refresher:
  refreshInterval: 10
  fetchInterval: 60
update:
  method: prompt
  days: 14
