font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

adjust_line_height    0
adjust_column_width   0

cursor_blink_interval      2.0
cursor_stop_blinking_after 5.0
cursor_trail               3

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

background_opacity 0.70

map shift+insert paste_from_clipboard
map ctrl+backspace send_text all \x17
map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u

allow_remote_control yes

shell_integration no-cursor
cursor_shape block
cursor_blink_interval 0
enable_audio_bell no

tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell zsh
editor nvim
term xterm-256color
strip_trailing_spaces smart
update_check_interval 7
