font_family JetBrainsMono Nerd Font
font_size 12

enabled_layouts splits,stack

close_on_child_death no

confirm_os_window_close 0

window_padding_width 20

background_opacity 0.78

map shift+insert paste_from_clipboard

shell_integration no-cursor
cursor_shape block

touch_scroll_multiplier 8
