$background = 0e0e0e
$onBackground = e5e5e5
$surface = 0e0e0e
$surfaceDim = 0e0e0e
$surfaceBright = 2c2c2c
$surfaceContainerLowest = 000000
$surfaceContainerLow = 141414
$surfaceContainer = 1a1a1a
$surfaceContainerHigh = 202020
$surfaceContainerHighest = 262626
$onSurface = e5e5e5
$surfaceVariant = 262626
$onSurfaceVariant = ababab
$outline = 767676
$outlineVariant = 474747
$inverseSurface = f9f9f9
$inverseOnSurface = 555555
$shadow = 000000
$scrim = 000000
$surfaceTint = c7c7c7
$primary = c7c7c7
$primaryDim = b9b9b9
$onPrimary = 404040
$primaryContainer = 474747
$onPrimaryContainer = d0d0d0
$inversePrimary = 5f5f5f
$primaryFixed = e2e2e2
$primaryFixedDim = d5d5d5
$onPrimaryFixed = 3f3f3f
$onPrimaryFixedVariant = 5c5c5c
$secondary = 9e9e9e
$secondaryDim = 9e9e9e
$onSecondary = 202020
$secondaryContainer = 3b3b3b
$onSecondaryContainer = bfbfbf
$secondaryFixed = e3e3e3
$secondaryFixedDim = d4d4d4
$onSecondaryFixed = 3f3f3f
$onSecondaryFixedVariant = 5c5c5c
$tertiary = e8e8e8
$tertiaryDim = e5d6d9
$onTertiary = 5c5354
$tertiaryContainer = e5d6d9
$onTertiaryContainer = 544b4c
$tertiaryFixed = e5d6d9
$tertiaryFixedDim = d6c9cb
$onTertiaryFixed = 40383a
$onTertiaryFixedVariant = 5d5455
$error = d78890
$errorDim = a76068
$onError = 3f0f17
$errorContainer = 71333c
$onErrorContainer = e8a2a9
$primaryPaletteKeyColor = 777777
$secondaryPaletteKeyColor = 777777
$tertiaryPaletteKeyColor = 777777
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 777777
$errorPaletteKeyColor = ab626a
$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 777777
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$term0 = 343434
$term1 = f06447
$term2 = e5c5b6
$term3 = e5e5e5
$term4 = b3ab8a
$term5 = db9a93
$term6 = e8c2a9
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = eb917e
$term10 = e3dcda
$term11 = f4f4f4
$term12 = c9bfb6
$term13 = e6b3ac
$term14 = e4d9d3
$term15 = ffffff
$rosewater = f1f1f1
$flamingo = e1e1e1
$pink = e2dbda
$mauve = e6b4b6
$red = e8a39a
$maroon = e0b4ad
$peach = e3c8c0
$yellow = f1f1f1
$green = e4dedc
$teal = f1ddbc
$sky = e0ddab
$sapphire = e3bbe0
$blue = e8adbc
$lavender = e5c5c8
$klink = ae7697
$klinkSelection = ae7697
$kvisited = bd686a
$kvisitedSelection = bd686a
$knegative = dc624d
$knegativeSelection = dc634d
$kneutral = eb947a
$kneutralSelection = eb947a
$kpositive = eb954d
$kpositiveSelection = eb954d
$text = e5e5e5
$subtext1 = ababab
$subtext0 = 767676
$overlay2 = 676767
$overlay1 = 585858
$overlay0 = 494949
$surface2 = 3b3b3b
$surface1 = 2d2d2d
$surface0 = 1d1d1d
$base = 0e0e0e
$mantle = 0e0e0e
$crust = 0d0d0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
