[theme]
name = "kanagawa"

[colors]
AlertInfo = "#8a9a7b"
AlertError = "#e46876"
AlertWarn = "#e6c384"
Annotation = "#a292a3"
Base = "#e6bd7d"
# Guidance = "#7fb4ca"
Guidance = "#ff9e3b"
Muted = "#54546d"
Important = "#ff9e3b"
Title = "#6a9589"
